# Generated by Django 4.0.8 on 2022-11-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='tags',
        ),
        migrations.AddField(
            model_name='todolist',
            name='tag_list',
            field=models.ManyToManyField(related_name='tages', to='mainapp.tags'),
        ),
    ]
