# Generated by Django 4.0.8 on 2022-11-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_tags_remove_todolist_tags_todolist_tag_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
