# Generated by Django 4.0.8 on 2022-11-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_tag_remove_todolist_tags_todolist_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='tags',
            field=models.ManyToManyField(blank=True, to='mainapp.tag'),
        ),
    ]
