# Generated by Django 4.0.8 on 2022-11-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_tags_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='tag_list',
        ),
        migrations.AddField(
            model_name='todolist',
            name='tags',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
